apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zp6g7t9uy-dotnet-basic
  janus-idp.io/tekton: zp6g7t9uy-dotnet-basic
  backstage.io/kubernetes-id: zp6g7t9uy-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zp6g7t9uy-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
